import { TypeDataSkill } from "./type_data.skill";

export const DataDumySkill: TypeDataSkill[] = [
    { id: 1, name: "JavaScript", level: "Intermediate" },
    { id: 2, name: "TypeScript", level: "Intermediate" },
    { id: 3, name: "React", level: "Intermediate" },
    { id: 4, name: "NextJS", level: "Intermediate" },
    { id: 5, name: "TailwindCSS", level: "Intermediate" },
    { id: 6, name: "NodeJS", level: "Intermediate" },
    { id: 7, name: "ExpressJS", level: "Intermediate" },
    { id: 8, name: "NestJS", level: "Intermediate" },
    { id: 9, name: "Prisma", level: "Intermediate" },
    { id: 10, name: "MongoDB", level: "Intermediate" },
    { id: 11, name: "MySQL", level: "Intermediate" },
    { id: 12, name: "PostgreSQL", level: "Intermediate" },
    { id: 13, name: "GraphQL", level: "Intermediate" },
    { id: 14, name: "Git", level: "Intermediate" },
    { id: 15, name: "Docker", level: "Intermediate" },
    { id: 16, name: "Kubernetes", level: "Intermediate" },
    { id: 17, name: "AWS", level: "Intermediate" },
    { id: 18, name: "Azure", level: "Intermediate" },
    { id: 19, name: "GCP", level: "Intermediate" },
    { id: 20, name: "Python", level: "Intermediate" },
    { id: 21, name: "Java", level: "Intermediate" },
    { id: 22, name: "C++", level: "Intermediate" },
    { id: 23, name: "C#", level: "Intermediate" },
    { id: 24, name: "Ruby", level: "Intermediate" },
    { id: 25, name: "PHP", level: "Intermediate" },
    { id: 26, name: "Swift", level: "Intermediate" },
    { id: 27, name: "Kotlin", level: "Intermediate" },]