// -----------------------------------------------------------
// import dependencies like next, react, or any other
// -----------------------------------------------------------
import { Poppins } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";

// -----------------------------------------------------------
// import layout
// -----------------------------------------------------------
import Master from "@/components/Master";

// -----------------------------------------------------------
// configure metadata
// -----------------------------------------------------------
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// -----------------------------------------------------------
// configure poppins font
// -----------------------------------------------------------
const poppins = Poppins({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-poppins',
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

// -----------------------------------------------------------
// configure root layout
// -----------------------------------------------------------
export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en" data-theme="dark">
            <body className={`${poppins.variable} antialiased select-none`}>
                <Master>
                    {children}
                </Master>
            </body>
        </html>
    );
}
